services:
  postgres:
    environment:
      POSTGRES_USER: "econia"
      POSTGRES_DB: "econia"
      POSTGRES_PASSWORD: "econia"
    image: postgres:14-bookworm
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "db:/var/lib/postgresql/data"
    healthcheck:
      test: pg_isready -h localhost -p 5432 -U econia || exit 1
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s
      start_interval: 5s

  postgrest:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGRST_DB_URI: "postgres://econia:econia@postgres:5432/econia"
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_MAX_ROWS: ${POSTGREST_MAX_ROWS}
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    restart: unless-stopped

  processor:
    build:
      context: .
      dockerfile: processor/rust/Dockerfile
    environment:
      DATABASE_URL: "postgres://econia:econia@postgres:5432/econia"
      CONTRACT_ADDRESS: ${CONTRACT_ADDRESS}
      GRPC_AUTH_TOKEN: ${GRPC_AUTH_TOKEN}
      GRPC_DATA_SERVICE_URL: ${GRPC_DATA_SERVICE_URL}
      STARTING_VERSION: ${STARTING_VERSION}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db:
    driver: local
