CREATE TABLE sql_extensions(
    name TEXT PRIMARY KEY
);


CREATE USER web_anon NOLOGIN;
GRANT SELECT ON ALL TABLES IN SCHEMA public to web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO web_anon;
