CREATE TABLE sql_extensions (
    name TEXT PRIMARY KEY
);


CREATE USER web_anon NOLOGIN;
GRANT web_anon TO postgres;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO web_anon;
